version: "3.1"

services:
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: alfa-php 
        volumes:
            - ./:/var/www/html/ 
        ports: 
            - "80:80"
            - "443:443"
